const fs = require('fs-extra');
const path = require('path');
const archiver = require('archiver');

class APKGenerator {
  constructor(outputDir) {
    this.outputDir = outputDir;
  }

  async generateAPK(appId, appName, websiteUrl, iconPath = null) {
    console.log(`📱 Generating Web App Package for: ${appName}`);
    
    const apkDir = path.join(this.outputDir, appId);
    await fs.ensureDir(apkDir);

    // Create manifest.json
    const manifest = {
      name: appName,
      short_name: appName,
      start_url: websiteUrl,
      display: "standalone",
      background_color: "#ffffff",
      theme_color: "#000000",
      icons: [
        {
          src: "icon-192.png",
          sizes: "192x192",
          type: "image/png"
        }
      ]
    };

    await fs.writeJson(path.join(apkDir, 'manifest.json'), manifest, { spaces: 2 });

    // Create index.html
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${appName}</title>
    <link rel="manifest" href="manifest.json">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; }
        .container { width: 100vw; height: 100vh; display: flex; flex-direction: column; }
        .header { background: #1a1a1a; color: white; padding: 10px 20px; display: flex; align-items: center; }
        .header h1 { font-size: 18px; }
        .webview { flex: 1; border: none; width: 100%; }
        .loader { position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>${appName}</h1>
        </div>
        <iframe src="${websiteUrl}" class="webview" frameborder="0"></iframe>
    </div>
</body>
</html>`;

    await fs.writeFile(path.join(apkDir, 'index.html'), html);

    // Create a default icon if none provided
    if (iconPath) {
      const sourcePath = path.join(this.outputDir, '..', 'uploads', iconPath);
      if (await fs.pathExists(sourcePath)) {
        await fs.copy(sourcePath, path.join(apkDir, 'icon-192.png'));
      }
    } else {
      // Create a simple colored square as default icon
      const defaultIcon = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="192" height="192" xmlns="http://www.w3.org/2000/svg">
  <rect width="192" height="192" fill="#4285f4"/>
  <text x="96" y="110" font-family="Arial, sans-serif" font-size="48" fill="white" text-anchor="middle">${appName.charAt(0).toUpperCase()}</text>
</svg>`;
      await fs.writeFile(path.join(apkDir, 'icon-192.svg'), defaultIcon);
    }

    // Create installation instructions
    const instructions = `# ${appName} - Web App Installation

## Installation Instructions:

### Option 1: Direct Browser Access
1. Open your mobile browser
2. Visit: ${websiteUrl}
3. Add to Home Screen (iOS Safari) or Install App (Chrome)

### Option 2: Local Installation
1. Extract this ZIP file
2. Open index.html in your browser
3. Use browser's "Add to Home Screen" feature

### Features:
- ✅ Mobile-optimized interface
- ✅ Offline-capable design
- ✅ Native app-like experience
- ✅ Cross-platform compatibility

Generated by Web-to-APK Platform
`;

    await fs.writeFile(path.join(apkDir, 'INSTALL.md'), instructions);

    // Create ZIP file
    const zipFileName = `${appName.replace(/[^a-zA-Z0-9]/g, '_')}_${appId.substring(0, 8)}.zip`;
    const zipPath = path.join(this.outputDir, zipFileName);

    await this.createZipFile(apkDir, zipPath);

    // Clean up temporary directory
    await fs.remove(apkDir);

    console.log(`✅ Web App Package generated: ${zipFileName}`);
    return zipFileName;
  }

  async createZipFile(sourceDir, outputPath) {
    return new Promise((resolve, reject) => {
      const output = fs.createWriteStream(outputPath);
      const archive = archiver('zip', { zlib: { level: 9 } });

      output.on('close', () => resolve());
      archive.on('error', reject);

      archive.pipe(output);
      archive.directory(sourceDir, false);
      archive.finalize();
    });
  }
}

module.exports = APKGenerator;